### ISSUE TITLE
Week 2 Practical

### ISSUE THREAD

**Issue by ndh2np** [josephwan21/BEDApr2024Apr_P06_S10262528#1]
Hi @josephwan21,

Have you completed Week 2 Practical?
If yes, please push the code from your local repository to this Github repository.

Thanks

**Comment by josephwan21** [comment]
Alright just pushed it @ndh2np

**Comment by josephwan21** [comment]
apologies but i think i was supposed to name my commit as "Complete Practical 2" but named it as "Add week 2 materials"

**Comment by josephwan21** [comment]
alright changed it
